// Code generated by protoc-gen-go. DO NOT EDIT.
// source: third_party.proto

package thirdpartyrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EndThirdPartyParams struct {
	Params               *GetThirdPartyParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	EndAtMonth           int32                `protobuf:"varint,2,opt,name=end_at_month,json=endAtMonth,proto3" json:"end_at_month,omitempty"`
	EndAtDay             int32                `protobuf:"varint,3,opt,name=end_at_day,json=endAtDay,proto3" json:"end_at_day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EndThirdPartyParams) Reset()         { *m = EndThirdPartyParams{} }
func (m *EndThirdPartyParams) String() string { return proto.CompactTextString(m) }
func (*EndThirdPartyParams) ProtoMessage()    {}
func (*EndThirdPartyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e319316a0c7196, []int{0}
}

func (m *EndThirdPartyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndThirdPartyParams.Unmarshal(m, b)
}
func (m *EndThirdPartyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndThirdPartyParams.Marshal(b, m, deterministic)
}
func (m *EndThirdPartyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndThirdPartyParams.Merge(m, src)
}
func (m *EndThirdPartyParams) XXX_Size() int {
	return xxx_messageInfo_EndThirdPartyParams.Size(m)
}
func (m *EndThirdPartyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EndThirdPartyParams.DiscardUnknown(m)
}

var xxx_messageInfo_EndThirdPartyParams proto.InternalMessageInfo

func (m *EndThirdPartyParams) GetParams() *GetThirdPartyParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *EndThirdPartyParams) GetEndAtMonth() int32 {
	if m != nil {
		return m.EndAtMonth
	}
	return 0
}

func (m *EndThirdPartyParams) GetEndAtDay() int32 {
	if m != nil {
		return m.EndAtDay
	}
	return 0
}

type GetThirdPartyParams struct {
	Id                      int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InAppPurchaseSku        string   `protobuf:"bytes,2,opt,name=in_app_purchase_sku,json=inAppPurchaseSku,proto3" json:"in_app_purchase_sku,omitempty"`
	GoogleBillingServiceSku string   `protobuf:"bytes,3,opt,name=google_billing_service_sku,json=googleBillingServiceSku,proto3" json:"google_billing_service_sku,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *GetThirdPartyParams) Reset()         { *m = GetThirdPartyParams{} }
func (m *GetThirdPartyParams) String() string { return proto.CompactTextString(m) }
func (*GetThirdPartyParams) ProtoMessage()    {}
func (*GetThirdPartyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e319316a0c7196, []int{1}
}

func (m *GetThirdPartyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThirdPartyParams.Unmarshal(m, b)
}
func (m *GetThirdPartyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThirdPartyParams.Marshal(b, m, deterministic)
}
func (m *GetThirdPartyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThirdPartyParams.Merge(m, src)
}
func (m *GetThirdPartyParams) XXX_Size() int {
	return xxx_messageInfo_GetThirdPartyParams.Size(m)
}
func (m *GetThirdPartyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThirdPartyParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetThirdPartyParams proto.InternalMessageInfo

func (m *GetThirdPartyParams) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetThirdPartyParams) GetInAppPurchaseSku() string {
	if m != nil {
		return m.InAppPurchaseSku
	}
	return ""
}

func (m *GetThirdPartyParams) GetGoogleBillingServiceSku() string {
	if m != nil {
		return m.GoogleBillingServiceSku
	}
	return ""
}

type CreateThirdPartyParams struct {
	InAppPurchaseSku        string   `protobuf:"bytes,1,opt,name=in_app_purchase_sku,json=inAppPurchaseSku,proto3" json:"in_app_purchase_sku,omitempty"`
	GoogleBillingServiceSku string   `protobuf:"bytes,2,opt,name=google_billing_service_sku,json=googleBillingServiceSku,proto3" json:"google_billing_service_sku,omitempty"`
	StartAtMonth            int32    `protobuf:"varint,3,opt,name=start_at_month,json=startAtMonth,proto3" json:"start_at_month,omitempty"`
	StartAtDay              int32    `protobuf:"varint,4,opt,name=start_at_day,json=startAtDay,proto3" json:"start_at_day,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *CreateThirdPartyParams) Reset()         { *m = CreateThirdPartyParams{} }
func (m *CreateThirdPartyParams) String() string { return proto.CompactTextString(m) }
func (*CreateThirdPartyParams) ProtoMessage()    {}
func (*CreateThirdPartyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e319316a0c7196, []int{2}
}

func (m *CreateThirdPartyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThirdPartyParams.Unmarshal(m, b)
}
func (m *CreateThirdPartyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThirdPartyParams.Marshal(b, m, deterministic)
}
func (m *CreateThirdPartyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThirdPartyParams.Merge(m, src)
}
func (m *CreateThirdPartyParams) XXX_Size() int {
	return xxx_messageInfo_CreateThirdPartyParams.Size(m)
}
func (m *CreateThirdPartyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThirdPartyParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThirdPartyParams proto.InternalMessageInfo

func (m *CreateThirdPartyParams) GetInAppPurchaseSku() string {
	if m != nil {
		return m.InAppPurchaseSku
	}
	return ""
}

func (m *CreateThirdPartyParams) GetGoogleBillingServiceSku() string {
	if m != nil {
		return m.GoogleBillingServiceSku
	}
	return ""
}

func (m *CreateThirdPartyParams) GetStartAtMonth() int32 {
	if m != nil {
		return m.StartAtMonth
	}
	return 0
}

func (m *CreateThirdPartyParams) GetStartAtDay() int32 {
	if m != nil {
		return m.StartAtDay
	}
	return 0
}

type GetThirdPartiesParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThirdPartiesParams) Reset()         { *m = GetThirdPartiesParams{} }
func (m *GetThirdPartiesParams) String() string { return proto.CompactTextString(m) }
func (*GetThirdPartiesParams) ProtoMessage()    {}
func (*GetThirdPartiesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e319316a0c7196, []int{3}
}

func (m *GetThirdPartiesParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThirdPartiesParams.Unmarshal(m, b)
}
func (m *GetThirdPartiesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThirdPartiesParams.Marshal(b, m, deterministic)
}
func (m *GetThirdPartiesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThirdPartiesParams.Merge(m, src)
}
func (m *GetThirdPartiesParams) XXX_Size() int {
	return xxx_messageInfo_GetThirdPartiesParams.Size(m)
}
func (m *GetThirdPartiesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThirdPartiesParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetThirdPartiesParams proto.InternalMessageInfo

type ThirdParty struct {
	Id                      int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InAppPurchaseSku        string   `protobuf:"bytes,2,opt,name=in_app_purchase_sku,json=inAppPurchaseSku,proto3" json:"in_app_purchase_sku,omitempty"`
	GoogleBillingServiceSku string   `protobuf:"bytes,3,opt,name=google_billing_service_sku,json=googleBillingServiceSku,proto3" json:"google_billing_service_sku,omitempty"`
	StartAt                 string   `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                   string   `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ThirdParty) Reset()         { *m = ThirdParty{} }
func (m *ThirdParty) String() string { return proto.CompactTextString(m) }
func (*ThirdParty) ProtoMessage()    {}
func (*ThirdParty) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e319316a0c7196, []int{4}
}

func (m *ThirdParty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdParty.Unmarshal(m, b)
}
func (m *ThirdParty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdParty.Marshal(b, m, deterministic)
}
func (m *ThirdParty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdParty.Merge(m, src)
}
func (m *ThirdParty) XXX_Size() int {
	return xxx_messageInfo_ThirdParty.Size(m)
}
func (m *ThirdParty) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdParty.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdParty proto.InternalMessageInfo

func (m *ThirdParty) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ThirdParty) GetInAppPurchaseSku() string {
	if m != nil {
		return m.InAppPurchaseSku
	}
	return ""
}

func (m *ThirdParty) GetGoogleBillingServiceSku() string {
	if m != nil {
		return m.GoogleBillingServiceSku
	}
	return ""
}

func (m *ThirdParty) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *ThirdParty) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

type GetThirdPartiesResponse struct {
	ThirdParties         []*ThirdParty `protobuf:"bytes,1,rep,name=third_parties,json=thirdParties,proto3" json:"third_parties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetThirdPartiesResponse) Reset()         { *m = GetThirdPartiesResponse{} }
func (m *GetThirdPartiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetThirdPartiesResponse) ProtoMessage()    {}
func (*GetThirdPartiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e319316a0c7196, []int{5}
}

func (m *GetThirdPartiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThirdPartiesResponse.Unmarshal(m, b)
}
func (m *GetThirdPartiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThirdPartiesResponse.Marshal(b, m, deterministic)
}
func (m *GetThirdPartiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThirdPartiesResponse.Merge(m, src)
}
func (m *GetThirdPartiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetThirdPartiesResponse.Size(m)
}
func (m *GetThirdPartiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThirdPartiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetThirdPartiesResponse proto.InternalMessageInfo

func (m *GetThirdPartiesResponse) GetThirdParties() []*ThirdParty {
	if m != nil {
		return m.ThirdParties
	}
	return nil
}

func init() {
	proto.RegisterType((*EndThirdPartyParams)(nil), "pepeunlimited.products.EndThirdPartyParams")
	proto.RegisterType((*GetThirdPartyParams)(nil), "pepeunlimited.products.GetThirdPartyParams")
	proto.RegisterType((*CreateThirdPartyParams)(nil), "pepeunlimited.products.CreateThirdPartyParams")
	proto.RegisterType((*GetThirdPartiesParams)(nil), "pepeunlimited.products.GetThirdPartiesParams")
	proto.RegisterType((*ThirdParty)(nil), "pepeunlimited.products.ThirdParty")
	proto.RegisterType((*GetThirdPartiesResponse)(nil), "pepeunlimited.products.GetThirdPartiesResponse")
}

func init() { proto.RegisterFile("third_party.proto", fileDescriptor_66e319316a0c7196) }

var fileDescriptor_66e319316a0c7196 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x4f, 0x6f, 0x12, 0x41,
	0x14, 0xcf, 0x82, 0x60, 0xfb, 0x0a, 0x6d, 0x1d, 0x52, 0xc0, 0xd5, 0x18, 0xb2, 0xf1, 0x40, 0x62,
	0x0a, 0x09, 0x1e, 0x3d, 0xb5, 0xd5, 0xf4, 0x64, 0x42, 0x16, 0x4f, 0x5e, 0xb6, 0x03, 0xf3, 0x0a,
	0x13, 0x60, 0x76, 0x9c, 0x99, 0xd5, 0xf0, 0x31, 0xbc, 0xfa, 0x45, 0x4c, 0xfc, 0x0c, 0x7e, 0x28,
	0xb3, 0x33, 0xcb, 0x9f, 0xae, 0x60, 0x56, 0x2f, 0xde, 0x36, 0xf3, 0xde, 0xdb, 0xdf, 0x9f, 0xf9,
	0xcd, 0x83, 0x27, 0x66, 0xc6, 0x15, 0x8b, 0x24, 0x55, 0x66, 0xd5, 0x93, 0x2a, 0x36, 0x31, 0x69,
	0x4a, 0x94, 0x98, 0x88, 0x05, 0x5f, 0x72, 0x83, 0x2c, 0x3d, 0x64, 0xc9, 0xc4, 0x68, 0xff, 0xd9,
	0x34, 0x8e, 0xa7, 0x0b, 0xec, 0xdb, 0xae, 0x71, 0x72, 0xdf, 0xc7, 0xa5, 0x5c, 0x0f, 0xf9, 0x2f,
	0xf2, 0xc5, 0x2f, 0x8a, 0x4a, 0x89, 0x4a, 0xbb, 0x7a, 0xf0, 0xcd, 0x83, 0xc6, 0x3b, 0xc1, 0x3e,
	0xa4, 0x68, 0xc3, 0x14, 0x6c, 0x48, 0x15, 0x5d, 0x6a, 0x72, 0x03, 0x55, 0x69, 0xbf, 0xda, 0x5e,
	0xc7, 0xeb, 0x9e, 0x0c, 0x5e, 0xf5, 0xf6, 0xa3, 0xf7, 0x6e, 0xd1, 0xe4, 0x87, 0xc3, 0x6c, 0x94,
	0x74, 0xa0, 0x86, 0x82, 0x45, 0xd4, 0x44, 0xcb, 0x58, 0x98, 0x59, 0xbb, 0xd4, 0xf1, 0xba, 0x95,
	0x10, 0x50, 0xb0, 0x2b, 0xf3, 0x3e, 0x3d, 0x21, 0xcf, 0x01, 0xb2, 0x0e, 0x46, 0x57, 0xed, 0xb2,
	0xad, 0x1f, 0xd9, 0xfa, 0x5b, 0xba, 0x0a, 0xbe, 0x7a, 0xd0, 0xd8, 0xf3, 0x7f, 0x72, 0x0a, 0x25,
	0xce, 0x2c, 0xb1, 0x4a, 0x58, 0xe2, 0x8c, 0x5c, 0x42, 0x83, 0x8b, 0x88, 0x4a, 0x19, 0xc9, 0x44,
	0x4d, 0x66, 0x54, 0x63, 0xa4, 0xe7, 0x89, 0x85, 0x3b, 0x0e, 0xcf, 0xb9, 0xb8, 0x92, 0x72, 0x98,
	0x15, 0x46, 0xf3, 0x84, 0xbc, 0x01, 0xdf, 0xb9, 0x12, 0x8d, 0xf9, 0x62, 0xc1, 0xc5, 0x34, 0xd2,
	0xa8, 0x3e, 0xf3, 0x89, 0x9b, 0x2a, 0xdb, 0xa9, 0x96, 0xeb, 0xb8, 0x76, 0x0d, 0x23, 0x57, 0x1f,
	0xcd, 0x93, 0xe0, 0xa7, 0x07, 0xcd, 0x1b, 0x85, 0xd4, 0xe0, 0x6f, 0xb4, 0x0e, 0xd0, 0xf0, 0xfe,
	0x89, 0x46, 0xe9, 0x8f, 0x34, 0xc8, 0x4b, 0x38, 0xd5, 0x86, 0x2a, 0xb3, 0x35, 0xd7, 0x99, 0x57,
	0xb3, 0xa7, 0x6b, 0x7b, 0x3b, 0x50, 0xdb, 0x74, 0xa5, 0x06, 0x3f, 0x72, 0x17, 0x90, 0xf5, 0xa4,
	0x16, 0xb7, 0xe0, 0x62, 0xd7, 0x61, 0x8e, 0xda, 0x89, 0x09, 0x7e, 0x78, 0x00, 0x5b, 0x85, 0xff,
	0xd3, 0x72, 0xf2, 0x14, 0x8e, 0xd6, 0x2a, 0xac, 0x82, 0xe3, 0xf0, 0x71, 0xa6, 0x80, 0x5c, 0x40,
	0xd5, 0xe5, 0xa7, 0x5d, 0xb1, 0x85, 0x8a, 0xcd, 0x4e, 0x30, 0x86, 0x56, 0x4e, 0x55, 0x88, 0x5a,
	0xc6, 0x42, 0x23, 0xb9, 0x85, 0xfa, 0xf6, 0x69, 0x71, 0x4c, 0xf3, 0x5d, 0xee, 0x9e, 0x0c, 0x82,
	0x43, 0xf9, 0xde, 0x7a, 0x10, 0xd6, 0xcc, 0xce, 0x0f, 0x07, 0xdf, 0xcb, 0xd0, 0xdc, 0x89, 0x80,
	0x4a, 0xc9, 0x3a, 0xce, 0xe4, 0x1e, 0xce, 0xf3, 0x11, 0x21, 0xbd, 0x43, 0x00, 0xfb, 0xc3, 0xe4,
	0x17, 0x20, 0x44, 0x3e, 0xc1, 0x59, 0x4e, 0x26, 0xb9, 0x2c, 0xf2, 0x4e, 0x37, 0xb7, 0xec, 0xf7,
	0x0b, 0xb6, 0x6f, 0xec, 0xbb, 0x83, 0xfa, 0x83, 0x17, 0x49, 0xfe, 0x66, 0x31, 0x14, 0x12, 0x75,
	0x07, 0xf5, 0x07, 0x0b, 0xe9, 0x30, 0xc2, 0x9e, 0xbd, 0x55, 0x04, 0xe1, 0xfa, 0xec, 0xa3, 0x8b,
	0x80, 0x5d, 0xae, 0x4a, 0x4e, 0xc6, 0x55, 0xbb, 0x0b, 0x5f, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x65, 0xb3, 0xe8, 0xed, 0x75, 0x05, 0x00, 0x00,
}
