// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/prices/internal/pkg/ent/iapsource"
	"github.com/pepeunlimited/prices/internal/pkg/ent/predicate"
	"github.com/pepeunlimited/prices/internal/pkg/ent/price"
)

// IapSourceQuery is the builder for querying IapSource entities.
type IapSourceQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.IapSource
	// eager-loading edges.
	withPrices *PriceQuery
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (isq *IapSourceQuery) Where(ps ...predicate.IapSource) *IapSourceQuery {
	isq.predicates = append(isq.predicates, ps...)
	return isq
}

// Limit adds a limit step to the query.
func (isq *IapSourceQuery) Limit(limit int) *IapSourceQuery {
	isq.limit = &limit
	return isq
}

// Offset adds an offset step to the query.
func (isq *IapSourceQuery) Offset(offset int) *IapSourceQuery {
	isq.offset = &offset
	return isq
}

// Order adds an order step to the query.
func (isq *IapSourceQuery) Order(o ...Order) *IapSourceQuery {
	isq.order = append(isq.order, o...)
	return isq
}

// QueryPrices chains the current query on the prices edge.
func (isq *IapSourceQuery) QueryPrices() *PriceQuery {
	query := &PriceQuery{config: isq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(iapsource.Table, iapsource.FieldID, isq.sqlQuery()),
		sqlgraph.To(price.Table, price.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, iapsource.PricesTable, iapsource.PricesColumn),
	)
	query.sql = sqlgraph.SetNeighbors(isq.driver.Dialect(), step)
	return query
}

// First returns the first IapSource entity in the query. Returns *NotFoundError when no iapsource was found.
func (isq *IapSourceQuery) First(ctx context.Context) (*IapSource, error) {
	isSlice, err := isq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(isSlice) == 0 {
		return nil, &NotFoundError{iapsource.Label}
	}
	return isSlice[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (isq *IapSourceQuery) FirstX(ctx context.Context) *IapSource {
	is, err := isq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return is
}

// FirstID returns the first IapSource id in the query. Returns *NotFoundError when no id was found.
func (isq *IapSourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = isq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{iapsource.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (isq *IapSourceQuery) FirstXID(ctx context.Context) int {
	id, err := isq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only IapSource entity in the query, returns an error if not exactly one entity was returned.
func (isq *IapSourceQuery) Only(ctx context.Context) (*IapSource, error) {
	isSlice, err := isq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(isSlice) {
	case 1:
		return isSlice[0], nil
	case 0:
		return nil, &NotFoundError{iapsource.Label}
	default:
		return nil, &NotSingularError{iapsource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (isq *IapSourceQuery) OnlyX(ctx context.Context) *IapSource {
	is, err := isq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return is
}

// OnlyID returns the only IapSource id in the query, returns an error if not exactly one id was returned.
func (isq *IapSourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = isq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{iapsource.Label}
	default:
		err = &NotSingularError{iapsource.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (isq *IapSourceQuery) OnlyXID(ctx context.Context) int {
	id, err := isq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IapSources.
func (isq *IapSourceQuery) All(ctx context.Context) ([]*IapSource, error) {
	return isq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (isq *IapSourceQuery) AllX(ctx context.Context) []*IapSource {
	isSlice, err := isq.All(ctx)
	if err != nil {
		panic(err)
	}
	return isSlice
}

// IDs executes the query and returns a list of IapSource ids.
func (isq *IapSourceQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := isq.Select(iapsource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (isq *IapSourceQuery) IDsX(ctx context.Context) []int {
	ids, err := isq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (isq *IapSourceQuery) Count(ctx context.Context) (int, error) {
	return isq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (isq *IapSourceQuery) CountX(ctx context.Context) int {
	count, err := isq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (isq *IapSourceQuery) Exist(ctx context.Context) (bool, error) {
	return isq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (isq *IapSourceQuery) ExistX(ctx context.Context) bool {
	exist, err := isq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (isq *IapSourceQuery) Clone() *IapSourceQuery {
	return &IapSourceQuery{
		config:     isq.config,
		limit:      isq.limit,
		offset:     isq.offset,
		order:      append([]Order{}, isq.order...),
		unique:     append([]string{}, isq.unique...),
		predicates: append([]predicate.IapSource{}, isq.predicates...),
		// clone intermediate query.
		sql: isq.sql.Clone(),
	}
}

//  WithPrices tells the query-builder to eager-loads the nodes that are connected to
// the "prices" edge. The optional arguments used to configure the query builder of the edge.
func (isq *IapSourceQuery) WithPrices(opts ...func(*PriceQuery)) *IapSourceQuery {
	query := &PriceQuery{config: isq.config}
	for _, opt := range opts {
		opt(query)
	}
	isq.withPrices = query
	return isq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InAppPurchaseSku string `json:"in_app_purchase_sku,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IapSource.Query().
//		GroupBy(iapsource.FieldInAppPurchaseSku).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (isq *IapSourceQuery) GroupBy(field string, fields ...string) *IapSourceGroupBy {
	group := &IapSourceGroupBy{config: isq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = isq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		InAppPurchaseSku string `json:"in_app_purchase_sku,omitempty"`
//	}
//
//	client.IapSource.Query().
//		Select(iapsource.FieldInAppPurchaseSku).
//		Scan(ctx, &v)
//
func (isq *IapSourceQuery) Select(field string, fields ...string) *IapSourceSelect {
	selector := &IapSourceSelect{config: isq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = isq.sqlQuery()
	return selector
}

func (isq *IapSourceQuery) sqlAll(ctx context.Context) ([]*IapSource, error) {
	var (
		nodes       = []*IapSource{}
		_spec       = isq.querySpec()
		loadedTypes = [1]bool{
			isq.withPrices != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &IapSource{config: isq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, isq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := isq.withPrices; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*IapSource)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Price(func(s *sql.Selector) {
			s.Where(sql.InValues(iapsource.PricesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.iap_source_prices
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "iap_source_prices" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "iap_source_prices" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Prices = append(node.Edges.Prices, n)
		}
	}

	return nodes, nil
}

func (isq *IapSourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := isq.querySpec()
	return sqlgraph.CountNodes(ctx, isq.driver, _spec)
}

func (isq *IapSourceQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := isq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (isq *IapSourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   iapsource.Table,
			Columns: iapsource.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: iapsource.FieldID,
			},
		},
		From:   isq.sql,
		Unique: true,
	}
	if ps := isq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := isq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := isq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := isq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (isq *IapSourceQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(isq.driver.Dialect())
	t1 := builder.Table(iapsource.Table)
	selector := builder.Select(t1.Columns(iapsource.Columns...)...).From(t1)
	if isq.sql != nil {
		selector = isq.sql
		selector.Select(selector.Columns(iapsource.Columns...)...)
	}
	for _, p := range isq.predicates {
		p(selector)
	}
	for _, p := range isq.order {
		p(selector)
	}
	if offset := isq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := isq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IapSourceGroupBy is the builder for group-by IapSource entities.
type IapSourceGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (isgb *IapSourceGroupBy) Aggregate(fns ...Aggregate) *IapSourceGroupBy {
	isgb.fns = append(isgb.fns, fns...)
	return isgb
}

// Scan applies the group-by query and scan the result into the given value.
func (isgb *IapSourceGroupBy) Scan(ctx context.Context, v interface{}) error {
	return isgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (isgb *IapSourceGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := isgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (isgb *IapSourceGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(isgb.fields) > 1 {
		return nil, errors.New("ent: IapSourceGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := isgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (isgb *IapSourceGroupBy) StringsX(ctx context.Context) []string {
	v, err := isgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (isgb *IapSourceGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(isgb.fields) > 1 {
		return nil, errors.New("ent: IapSourceGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := isgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (isgb *IapSourceGroupBy) IntsX(ctx context.Context) []int {
	v, err := isgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (isgb *IapSourceGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(isgb.fields) > 1 {
		return nil, errors.New("ent: IapSourceGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := isgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (isgb *IapSourceGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := isgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (isgb *IapSourceGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(isgb.fields) > 1 {
		return nil, errors.New("ent: IapSourceGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := isgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (isgb *IapSourceGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := isgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (isgb *IapSourceGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := isgb.sqlQuery().Query()
	if err := isgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (isgb *IapSourceGroupBy) sqlQuery() *sql.Selector {
	selector := isgb.sql
	columns := make([]string, 0, len(isgb.fields)+len(isgb.fns))
	columns = append(columns, isgb.fields...)
	for _, fn := range isgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(isgb.fields...)
}

// IapSourceSelect is the builder for select fields of IapSource entities.
type IapSourceSelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (iss *IapSourceSelect) Scan(ctx context.Context, v interface{}) error {
	return iss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (iss *IapSourceSelect) ScanX(ctx context.Context, v interface{}) {
	if err := iss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (iss *IapSourceSelect) Strings(ctx context.Context) ([]string, error) {
	if len(iss.fields) > 1 {
		return nil, errors.New("ent: IapSourceSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := iss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (iss *IapSourceSelect) StringsX(ctx context.Context) []string {
	v, err := iss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (iss *IapSourceSelect) Ints(ctx context.Context) ([]int, error) {
	if len(iss.fields) > 1 {
		return nil, errors.New("ent: IapSourceSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := iss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (iss *IapSourceSelect) IntsX(ctx context.Context) []int {
	v, err := iss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (iss *IapSourceSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(iss.fields) > 1 {
		return nil, errors.New("ent: IapSourceSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := iss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (iss *IapSourceSelect) Float64sX(ctx context.Context) []float64 {
	v, err := iss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (iss *IapSourceSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(iss.fields) > 1 {
		return nil, errors.New("ent: IapSourceSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := iss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (iss *IapSourceSelect) BoolsX(ctx context.Context) []bool {
	v, err := iss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (iss *IapSourceSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := iss.sqlQuery().Query()
	if err := iss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (iss *IapSourceSelect) sqlQuery() sql.Querier {
	selector := iss.sql
	selector.Select(selector.Columns(iss.fields...)...)
	return selector
}
