// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/products/internal/pkg/ent/plan"
	"github.com/pepeunlimited/products/internal/pkg/ent/product"
	"github.com/pepeunlimited/products/internal/pkg/ent/subscription"
	"github.com/pepeunlimited/products/internal/pkg/ent/thirdpartyprice"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	title_i18n_id      *int64
	length             *uint8
	start_at           *time.Time
	end_at             *time.Time
	price              *int64
	discount           *int64
	unit               *string
	subscriptions      map[int]struct{}
	products           map[int]struct{}
	third_party_prices map[int]struct{}
}

// SetTitleI18nID sets the title_i18n_id field.
func (pc *PlanCreate) SetTitleI18nID(i int64) *PlanCreate {
	pc.title_i18n_id = &i
	return pc
}

// SetLength sets the length field.
func (pc *PlanCreate) SetLength(u uint8) *PlanCreate {
	pc.length = &u
	return pc
}

// SetStartAt sets the start_at field.
func (pc *PlanCreate) SetStartAt(t time.Time) *PlanCreate {
	pc.start_at = &t
	return pc
}

// SetEndAt sets the end_at field.
func (pc *PlanCreate) SetEndAt(t time.Time) *PlanCreate {
	pc.end_at = &t
	return pc
}

// SetPrice sets the price field.
func (pc *PlanCreate) SetPrice(i int64) *PlanCreate {
	pc.price = &i
	return pc
}

// SetDiscount sets the discount field.
func (pc *PlanCreate) SetDiscount(i int64) *PlanCreate {
	pc.discount = &i
	return pc
}

// SetUnit sets the unit field.
func (pc *PlanCreate) SetUnit(s string) *PlanCreate {
	pc.unit = &s
	return pc
}

// AddSubscriptionIDs adds the subscriptions edge to Subscription by ids.
func (pc *PlanCreate) AddSubscriptionIDs(ids ...int) *PlanCreate {
	if pc.subscriptions == nil {
		pc.subscriptions = make(map[int]struct{})
	}
	for i := range ids {
		pc.subscriptions[ids[i]] = struct{}{}
	}
	return pc
}

// AddSubscriptions adds the subscriptions edges to Subscription.
func (pc *PlanCreate) AddSubscriptions(s ...*Subscription) *PlanCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pc.AddSubscriptionIDs(ids...)
}

// SetProductsID sets the products edge to Product by id.
func (pc *PlanCreate) SetProductsID(id int) *PlanCreate {
	if pc.products == nil {
		pc.products = make(map[int]struct{})
	}
	pc.products[id] = struct{}{}
	return pc
}

// SetNillableProductsID sets the products edge to Product by id if the given value is not nil.
func (pc *PlanCreate) SetNillableProductsID(id *int) *PlanCreate {
	if id != nil {
		pc = pc.SetProductsID(*id)
	}
	return pc
}

// SetProducts sets the products edge to Product.
func (pc *PlanCreate) SetProducts(p *Product) *PlanCreate {
	return pc.SetProductsID(p.ID)
}

// SetThirdPartyPricesID sets the third_party_prices edge to ThirdPartyPrice by id.
func (pc *PlanCreate) SetThirdPartyPricesID(id int) *PlanCreate {
	if pc.third_party_prices == nil {
		pc.third_party_prices = make(map[int]struct{})
	}
	pc.third_party_prices[id] = struct{}{}
	return pc
}

// SetNillableThirdPartyPricesID sets the third_party_prices edge to ThirdPartyPrice by id if the given value is not nil.
func (pc *PlanCreate) SetNillableThirdPartyPricesID(id *int) *PlanCreate {
	if id != nil {
		pc = pc.SetThirdPartyPricesID(*id)
	}
	return pc
}

// SetThirdPartyPrices sets the third_party_prices edge to ThirdPartyPrice.
func (pc *PlanCreate) SetThirdPartyPrices(t *ThirdPartyPrice) *PlanCreate {
	return pc.SetThirdPartyPricesID(t.ID)
}

// Save creates the Plan in the database.
func (pc *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	if pc.title_i18n_id == nil {
		return nil, errors.New("ent: missing required field \"title_i18n_id\"")
	}
	if pc.length == nil {
		return nil, errors.New("ent: missing required field \"length\"")
	}
	if pc.start_at == nil {
		return nil, errors.New("ent: missing required field \"start_at\"")
	}
	if pc.end_at == nil {
		return nil, errors.New("ent: missing required field \"end_at\"")
	}
	if pc.price == nil {
		return nil, errors.New("ent: missing required field \"price\"")
	}
	if pc.discount == nil {
		return nil, errors.New("ent: missing required field \"discount\"")
	}
	if pc.unit == nil {
		return nil, errors.New("ent: missing required field \"unit\"")
	}
	if err := plan.UnitValidator(*pc.unit); err != nil {
		return nil, fmt.Errorf("ent: validator failed for field \"unit\": %v", err)
	}
	if len(pc.products) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"products\"")
	}
	if len(pc.third_party_prices) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"third_party_prices\"")
	}
	return pc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	var (
		pl    = &Plan{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: plan.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: plan.FieldID,
			},
		}
	)
	if value := pc.title_i18n_id; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: plan.FieldTitleI18nID,
		})
		pl.TitleI18nID = *value
	}
	if value := pc.length; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  *value,
			Column: plan.FieldLength,
		})
		pl.Length = *value
	}
	if value := pc.start_at; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: plan.FieldStartAt,
		})
		pl.StartAt = *value
	}
	if value := pc.end_at; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: plan.FieldEndAt,
		})
		pl.EndAt = *value
	}
	if value := pc.price; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: plan.FieldPrice,
		})
		pl.Price = *value
	}
	if value := pc.discount; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  *value,
			Column: plan.FieldDiscount,
		})
		pl.Discount = *value
	}
	if value := pc.unit; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: plan.FieldUnit,
		})
		pl.Unit = *value
	}
	if nodes := pc.subscriptions; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subscription.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.products; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.ProductsTable,
			Columns: []string{plan.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.third_party_prices; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.ThirdPartyPricesTable,
			Columns: []string{plan.ThirdPartyPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: thirdpartyprice.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pl.ID = int(id)
	return pl, nil
}
