// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/prices/internal/pkg/ent/predicate"
	"github.com/pepeunlimited/prices/internal/pkg/ent/thirdparty"
)

// ThirdPartyDelete is the builder for deleting a ThirdParty entity.
type ThirdPartyDelete struct {
	config
	predicates []predicate.ThirdParty
}

// Where adds a new predicate to the delete builder.
func (tpd *ThirdPartyDelete) Where(ps ...predicate.ThirdParty) *ThirdPartyDelete {
	tpd.predicates = append(tpd.predicates, ps...)
	return tpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tpd *ThirdPartyDelete) Exec(ctx context.Context) (int, error) {
	return tpd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (tpd *ThirdPartyDelete) ExecX(ctx context.Context) int {
	n, err := tpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tpd *ThirdPartyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: thirdparty.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: thirdparty.FieldID,
			},
		},
	}
	if ps := tpd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tpd.driver, _spec)
}

// ThirdPartyDeleteOne is the builder for deleting a single ThirdParty entity.
type ThirdPartyDeleteOne struct {
	tpd *ThirdPartyDelete
}

// Exec executes the deletion query.
func (tpdo *ThirdPartyDeleteOne) Exec(ctx context.Context) error {
	n, err := tpdo.tpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{thirdparty.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tpdo *ThirdPartyDeleteOne) ExecX(ctx context.Context) {
	tpdo.tpd.ExecX(ctx)
}
