// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/prices/internal/pkg/ent/predicate"
	"github.com/pepeunlimited/prices/internal/pkg/ent/thirdpartyprice"
)

// ThirdPartyPriceDelete is the builder for deleting a ThirdPartyPrice entity.
type ThirdPartyPriceDelete struct {
	config
	predicates []predicate.ThirdPartyPrice
}

// Where adds a new predicate to the delete builder.
func (tppd *ThirdPartyPriceDelete) Where(ps ...predicate.ThirdPartyPrice) *ThirdPartyPriceDelete {
	tppd.predicates = append(tppd.predicates, ps...)
	return tppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tppd *ThirdPartyPriceDelete) Exec(ctx context.Context) (int, error) {
	return tppd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (tppd *ThirdPartyPriceDelete) ExecX(ctx context.Context) int {
	n, err := tppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tppd *ThirdPartyPriceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: thirdpartyprice.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: thirdpartyprice.FieldID,
			},
		},
	}
	if ps := tppd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tppd.driver, _spec)
}

// ThirdPartyPriceDeleteOne is the builder for deleting a single ThirdPartyPrice entity.
type ThirdPartyPriceDeleteOne struct {
	tppd *ThirdPartyPriceDelete
}

// Exec executes the deletion query.
func (tppdo *ThirdPartyPriceDeleteOne) Exec(ctx context.Context) error {
	n, err := tppdo.tppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{thirdpartyprice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tppdo *ThirdPartyPriceDeleteOne) ExecX(ctx context.Context) {
	tppdo.tppd.ExecX(ctx)
}
