// Code generated by protoc-gen-go. DO NOT EDIT.
// source: price.proto

package price

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EndPriceAtParams struct {
	Params               *GetPriceParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	EndAtDay             int32           `protobuf:"varint,2,opt,name=end_at_day,json=endAtDay,proto3" json:"end_at_day,omitempty"`
	EndAtMonth           int32           `protobuf:"varint,3,opt,name=end_at_month,json=endAtMonth,proto3" json:"end_at_month,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EndPriceAtParams) Reset()         { *m = EndPriceAtParams{} }
func (m *EndPriceAtParams) String() string { return proto.CompactTextString(m) }
func (*EndPriceAtParams) ProtoMessage()    {}
func (*EndPriceAtParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_94c214910ad4a3eb, []int{0}
}

func (m *EndPriceAtParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndPriceAtParams.Unmarshal(m, b)
}
func (m *EndPriceAtParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndPriceAtParams.Marshal(b, m, deterministic)
}
func (m *EndPriceAtParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndPriceAtParams.Merge(m, src)
}
func (m *EndPriceAtParams) XXX_Size() int {
	return xxx_messageInfo_EndPriceAtParams.Size(m)
}
func (m *EndPriceAtParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EndPriceAtParams.DiscardUnknown(m)
}

var xxx_messageInfo_EndPriceAtParams proto.InternalMessageInfo

func (m *EndPriceAtParams) GetParams() *GetPriceParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *EndPriceAtParams) GetEndAtDay() int32 {
	if m != nil {
		return m.EndAtDay
	}
	return 0
}

func (m *EndPriceAtParams) GetEndAtMonth() int32 {
	if m != nil {
		return m.EndAtMonth
	}
	return 0
}

type Price struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                uint32   `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Discount             uint32   `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	StartAt              string   `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	ThirdPartyId         int32    `protobuf:"varint,7,opt,name=third_party_id,json=thirdPartyId,proto3" json:"third_party_id,omitempty"`
	ProductId            int64    `protobuf:"varint,9,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_94c214910ad4a3eb, []int{1}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Price) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Price) GetDiscount() uint32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Price) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *Price) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

func (m *Price) GetThirdPartyId() int32 {
	if m != nil {
		return m.ThirdPartyId
	}
	return 0
}

func (m *Price) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type CreatePriceParams struct {
	StartAtDay           int32    `protobuf:"varint,1,opt,name=start_at_day,json=startAtDay,proto3" json:"start_at_day,omitempty"`
	StartAtMonth         int32    `protobuf:"varint,2,opt,name=start_at_month,json=startAtMonth,proto3" json:"start_at_month,omitempty"`
	EndAtDay             int32    `protobuf:"varint,3,opt,name=end_at_day,json=endAtDay,proto3" json:"end_at_day,omitempty"`
	EndAtMonth           int32    `protobuf:"varint,4,opt,name=end_at_month,json=endAtMonth,proto3" json:"end_at_month,omitempty"`
	Price                uint32   `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Discount             uint32   `protobuf:"varint,6,opt,name=discount,proto3" json:"discount,omitempty"`
	ProductId            int64    `protobuf:"varint,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ThirdPartyId         int32    `protobuf:"varint,9,opt,name=third_party_id,json=thirdPartyId,proto3" json:"third_party_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePriceParams) Reset()         { *m = CreatePriceParams{} }
func (m *CreatePriceParams) String() string { return proto.CompactTextString(m) }
func (*CreatePriceParams) ProtoMessage()    {}
func (*CreatePriceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_94c214910ad4a3eb, []int{2}
}

func (m *CreatePriceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePriceParams.Unmarshal(m, b)
}
func (m *CreatePriceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePriceParams.Marshal(b, m, deterministic)
}
func (m *CreatePriceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePriceParams.Merge(m, src)
}
func (m *CreatePriceParams) XXX_Size() int {
	return xxx_messageInfo_CreatePriceParams.Size(m)
}
func (m *CreatePriceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePriceParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePriceParams proto.InternalMessageInfo

func (m *CreatePriceParams) GetStartAtDay() int32 {
	if m != nil {
		return m.StartAtDay
	}
	return 0
}

func (m *CreatePriceParams) GetStartAtMonth() int32 {
	if m != nil {
		return m.StartAtMonth
	}
	return 0
}

func (m *CreatePriceParams) GetEndAtDay() int32 {
	if m != nil {
		return m.EndAtDay
	}
	return 0
}

func (m *CreatePriceParams) GetEndAtMonth() int32 {
	if m != nil {
		return m.EndAtMonth
	}
	return 0
}

func (m *CreatePriceParams) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreatePriceParams) GetDiscount() uint32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *CreatePriceParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *CreatePriceParams) GetThirdPartyId() int32 {
	if m != nil {
		return m.ThirdPartyId
	}
	return 0
}

type GetPriceParams struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductSku           string   `protobuf:"bytes,2,opt,name=product_sku,json=productSku,proto3" json:"product_sku,omitempty"`
	PriceId              int64    `protobuf:"varint,3,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceParams) Reset()         { *m = GetPriceParams{} }
func (m *GetPriceParams) String() string { return proto.CompactTextString(m) }
func (*GetPriceParams) ProtoMessage()    {}
func (*GetPriceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_94c214910ad4a3eb, []int{3}
}

func (m *GetPriceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceParams.Unmarshal(m, b)
}
func (m *GetPriceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceParams.Marshal(b, m, deterministic)
}
func (m *GetPriceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceParams.Merge(m, src)
}
func (m *GetPriceParams) XXX_Size() int {
	return xxx_messageInfo_GetPriceParams.Size(m)
}
func (m *GetPriceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceParams proto.InternalMessageInfo

func (m *GetPriceParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetPriceParams) GetProductSku() string {
	if m != nil {
		return m.ProductSku
	}
	return ""
}

func (m *GetPriceParams) GetPriceId() int64 {
	if m != nil {
		return m.PriceId
	}
	return 0
}

func init() {
	proto.RegisterType((*EndPriceAtParams)(nil), "pepeunlimited.products.EndPriceAtParams")
	proto.RegisterType((*Price)(nil), "pepeunlimited.products.Price")
	proto.RegisterType((*CreatePriceParams)(nil), "pepeunlimited.products.CreatePriceParams")
	proto.RegisterType((*GetPriceParams)(nil), "pepeunlimited.products.GetPriceParams")
}

func init() { proto.RegisterFile("price.proto", fileDescriptor_94c214910ad4a3eb) }

var fileDescriptor_94c214910ad4a3eb = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0x99, 0x74, 0xd3, 0x34, 0xa7, 0xdd, 0xa0, 0x83, 0x4a, 0x5c, 0x5c, 0x0c, 0x61, 0x91,
	0x78, 0xd3, 0x8b, 0xf5, 0x5e, 0xa8, 0x1f, 0x48, 0x2f, 0x84, 0x9a, 0x45, 0x04, 0x6f, 0xc2, 0xd8,
	0x19, 0xd8, 0xa1, 0x36, 0x09, 0x93, 0x13, 0xa1, 0x8f, 0xe1, 0x3e, 0x91, 0x8f, 0x26, 0x73, 0x26,
	0xdd, 0x8f, 0xec, 0x86, 0xee, 0x5d, 0xe7, 0x7c, 0xfc, 0xfb, 0x3f, 0xbf, 0x33, 0x13, 0x98, 0xd6,
	0x46, 0xaf, 0xd5, 0xbc, 0x36, 0x15, 0x56, 0xfc, 0x45, 0xad, 0x6a, 0xd5, 0x96, 0xbf, 0xf5, 0x56,
	0xa3, 0x92, 0x36, 0x28, 0xdb, 0x35, 0x36, 0xe9, 0x15, 0x83, 0x27, 0x9f, 0x4b, 0xb9, 0xb2, 0xa5,
	0x0b, 0x5c, 0x09, 0x23, 0xb6, 0x0d, 0x7f, 0x0f, 0xe3, 0x9a, 0x7e, 0xc5, 0x2c, 0x61, 0xd9, 0xf4,
	0xfc, 0xcd, 0xfc, 0xe1, 0xee, 0xf9, 0x17, 0x85, 0xd4, 0xe9, 0xfa, 0xf2, 0xae, 0x8b, 0xbf, 0x02,
	0x50, 0xa5, 0x2c, 0x04, 0x16, 0x52, 0xec, 0x62, 0x2f, 0x61, 0x99, 0x9f, 0x4f, 0x54, 0x29, 0x17,
	0xf8, 0x49, 0xec, 0x78, 0x02, 0xb3, 0x2e, 0xbb, 0xad, 0x4a, 0xbc, 0x8c, 0x47, 0x94, 0x07, 0xca,
	0x7f, 0xb5, 0x91, 0xf4, 0x1f, 0x03, 0x9f, 0x74, 0x79, 0x04, 0x9e, 0x96, 0xe4, 0x62, 0x94, 0x7b,
	0x5a, 0xf2, 0x67, 0xe0, 0xd3, 0x54, 0x24, 0x7a, 0x9c, 0xbb, 0x03, 0x3f, 0x81, 0x89, 0xd4, 0xcd,
	0xba, 0x6a, 0x4b, 0x24, 0xb5, 0xe3, 0xfc, 0xfa, 0xcc, 0x5f, 0xc2, 0xa4, 0x41, 0x61, 0xb0, 0x10,
	0x18, 0x1f, 0x25, 0x2c, 0x0b, 0xf3, 0x80, 0xce, 0x0b, 0xe4, 0xcf, 0x61, 0xec, 0x8c, 0xc4, 0x3e,
	0x25, 0x7c, 0xb2, 0xc0, 0xcf, 0x20, 0xc2, 0x4b, 0x6d, 0x64, 0x51, 0x0b, 0x83, 0xbb, 0x42, 0xcb,
	0x38, 0x20, 0x87, 0x33, 0x8a, 0xae, 0x6c, 0x70, 0x29, 0xf9, 0x29, 0x40, 0x87, 0xc1, 0x56, 0x84,
	0xe4, 0x30, 0xec, 0x22, 0x4b, 0x99, 0x5e, 0x79, 0xf0, 0xf4, 0xa3, 0x51, 0x02, 0xd5, 0x2d, 0x40,
	0x76, 0xf4, 0xbd, 0x19, 0x42, 0xc3, 0xdc, 0xe8, 0x9d, 0x21, 0x0b, 0xe7, 0x0c, 0xa2, 0xeb, 0x0a,
	0x87, 0xc7, 0xe1, 0x9b, 0x75, 0x35, 0x04, 0xa8, 0x07, 0x78, 0x74, 0x00, 0xf0, 0x51, 0x1f, 0xf0,
	0x0d, 0x46, 0x7f, 0x08, 0xe3, 0xb8, 0x87, 0xf1, 0xee, 0xb8, 0x41, 0x6f, 0xdc, 0x07, 0x98, 0x85,
	0xf7, 0x99, 0xa5, 0x1b, 0x88, 0xee, 0xde, 0x98, 0x9e, 0x2c, 0xeb, 0xcb, 0xbe, 0xb6, 0x97, 0xd8,
	0xa5, 0x9b, 0x4d, 0x4b, 0x28, 0xc2, 0x7c, 0xdf, 0x71, 0xb1, 0x69, 0xed, 0x76, 0xc9, 0xbb, 0xed,
	0x1e, 0x51, 0x77, 0x40, 0xe7, 0xa5, 0x3c, 0xff, 0xeb, 0xc1, 0x8c, 0xfe, 0xea, 0x42, 0x99, 0x3f,
	0x76, 0xbc, 0x1f, 0x30, 0xbd, 0xb5, 0x11, 0xfe, 0x76, 0xe8, 0x52, 0xdf, 0x5b, 0xdb, 0xc9, 0xe9,
	0x50, 0xa9, 0x53, 0xfa, 0x06, 0x93, 0xfd, 0x58, 0xfc, 0x91, 0x4f, 0xe5, 0x90, 0xe4, 0x77, 0x80,
	0x9b, 0x57, 0xc9, 0xb3, 0xa1, 0xe2, 0xfe, 0xcb, 0x3d, 0x20, 0xfb, 0x21, 0xf8, 0xe9, 0x56, 0xfd,
	0x6b, 0x4c, 0x5f, 0x85, 0x77, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x67, 0xe5, 0x9b, 0x10, 0x24,
	0x04, 0x00, 0x00,
}
