// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscription.proto

package subscriptionrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartSubscriptionParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId               int64    `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSubscriptionParams) Reset()         { *m = StartSubscriptionParams{} }
func (m *StartSubscriptionParams) String() string { return proto.CompactTextString(m) }
func (*StartSubscriptionParams) ProtoMessage()    {}
func (*StartSubscriptionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f8ad1a64b2bad6, []int{0}
}

func (m *StartSubscriptionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSubscriptionParams.Unmarshal(m, b)
}
func (m *StartSubscriptionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSubscriptionParams.Marshal(b, m, deterministic)
}
func (m *StartSubscriptionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSubscriptionParams.Merge(m, src)
}
func (m *StartSubscriptionParams) XXX_Size() int {
	return xxx_messageInfo_StartSubscriptionParams.Size(m)
}
func (m *StartSubscriptionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSubscriptionParams.DiscardUnknown(m)
}

var xxx_messageInfo_StartSubscriptionParams proto.InternalMessageInfo

func (m *StartSubscriptionParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StartSubscriptionParams) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

type GetSubscriptionParams struct {
	SubscriptionId       int64    `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionParams) Reset()         { *m = GetSubscriptionParams{} }
func (m *GetSubscriptionParams) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionParams) ProtoMessage()    {}
func (*GetSubscriptionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f8ad1a64b2bad6, []int{1}
}

func (m *GetSubscriptionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionParams.Unmarshal(m, b)
}
func (m *GetSubscriptionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionParams.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionParams.Merge(m, src)
}
func (m *GetSubscriptionParams) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionParams.Size(m)
}
func (m *GetSubscriptionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionParams proto.InternalMessageInfo

func (m *GetSubscriptionParams) GetSubscriptionId() int64 {
	if m != nil {
		return m.SubscriptionId
	}
	return 0
}

func (m *GetSubscriptionParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type StopSubscriptionParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSubscriptionParams) Reset()         { *m = StopSubscriptionParams{} }
func (m *StopSubscriptionParams) String() string { return proto.CompactTextString(m) }
func (*StopSubscriptionParams) ProtoMessage()    {}
func (*StopSubscriptionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f8ad1a64b2bad6, []int{2}
}

func (m *StopSubscriptionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSubscriptionParams.Unmarshal(m, b)
}
func (m *StopSubscriptionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSubscriptionParams.Marshal(b, m, deterministic)
}
func (m *StopSubscriptionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSubscriptionParams.Merge(m, src)
}
func (m *StopSubscriptionParams) XXX_Size() int {
	return xxx_messageInfo_StopSubscriptionParams.Size(m)
}
func (m *StopSubscriptionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSubscriptionParams.DiscardUnknown(m)
}

var xxx_messageInfo_StopSubscriptionParams proto.InternalMessageInfo

func (m *StopSubscriptionParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetSubscriptionsParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            int64    `protobuf:"varint,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionsParams) Reset()         { *m = GetSubscriptionsParams{} }
func (m *GetSubscriptionsParams) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionsParams) ProtoMessage()    {}
func (*GetSubscriptionsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f8ad1a64b2bad6, []int{3}
}

func (m *GetSubscriptionsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionsParams.Unmarshal(m, b)
}
func (m *GetSubscriptionsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionsParams.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionsParams.Merge(m, src)
}
func (m *GetSubscriptionsParams) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionsParams.Size(m)
}
func (m *GetSubscriptionsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionsParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionsParams proto.InternalMessageInfo

func (m *GetSubscriptionsParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetSubscriptionsParams) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetSubscriptionsParams) GetPageToken() int64 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

type GetSubscriptionsResponse struct {
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	NextPageToken        int64           `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetSubscriptionsResponse) Reset()         { *m = GetSubscriptionsResponse{} }
func (m *GetSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionsResponse) ProtoMessage()    {}
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f8ad1a64b2bad6, []int{4}
}

func (m *GetSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionsResponse.Unmarshal(m, b)
}
func (m *GetSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionsResponse.Merge(m, src)
}
func (m *GetSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionsResponse.Size(m)
}
func (m *GetSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionsResponse proto.InternalMessageInfo

func (m *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func (m *GetSubscriptionsResponse) GetNextPageToken() int64 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

type Subscription struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId               int64    `protobuf:"varint,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartAt              string   `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f8ad1a64b2bad6, []int{5}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Subscription) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Subscription) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

func (m *Subscription) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *Subscription) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

func init() {
	proto.RegisterType((*StartSubscriptionParams)(nil), "pepeunlimited.products.StartSubscriptionParams")
	proto.RegisterType((*GetSubscriptionParams)(nil), "pepeunlimited.products.GetSubscriptionParams")
	proto.RegisterType((*StopSubscriptionParams)(nil), "pepeunlimited.products.StopSubscriptionParams")
	proto.RegisterType((*GetSubscriptionsParams)(nil), "pepeunlimited.products.GetSubscriptionsParams")
	proto.RegisterType((*GetSubscriptionsResponse)(nil), "pepeunlimited.products.GetSubscriptionsResponse")
	proto.RegisterType((*Subscription)(nil), "pepeunlimited.products.Subscription")
}

func init() { proto.RegisterFile("subscription.proto", fileDescriptor_c4f8ad1a64b2bad6) }

var fileDescriptor_c4f8ad1a64b2bad6 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x6d, 0xf2, 0x37, 0x90, 0xbf, 0x45, 0x49, 0x4c, 0x10, 0x52, 0x64, 0x21, 0xc8, 0x05,
	0x03, 0xe1, 0x09, 0xc2, 0x05, 0x05, 0x2e, 0x91, 0xcd, 0x05, 0x2e, 0x96, 0x63, 0x0f, 0xb0, 0x34,
	0x59, 0xaf, 0xbc, 0xeb, 0xaa, 0xca, 0xb1, 0x0f, 0xd0, 0xf7, 0xea, 0x5b, 0x55, 0xeb, 0x28, 0xe9,
	0xc6, 0xb5, 0x55, 0xf7, 0xb8, 0xf3, 0x79, 0xe6, 0xfb, 0x66, 0xe6, 0x1b, 0x03, 0x11, 0xd9, 0x46,
	0x44, 0x29, 0xe5, 0x92, 0x26, 0xcc, 0xe5, 0x69, 0x22, 0x13, 0x32, 0xe6, 0xc8, 0x31, 0x63, 0x5b,
	0xba, 0xa3, 0x12, 0x63, 0x15, 0x8c, 0xb3, 0x48, 0x0a, 0xe7, 0x07, 0x4c, 0x7c, 0x19, 0xa6, 0xd2,
	0xd7, 0x52, 0xd6, 0x61, 0x1a, 0xee, 0x04, 0x99, 0x40, 0x2b, 0x13, 0x98, 0x06, 0x34, 0xb6, 0x8d,
	0x99, 0x31, 0xb7, 0xbc, 0xa6, 0x7a, 0xae, 0x62, 0x05, 0xf0, 0x6d, 0xc8, 0x14, 0x60, 0x1e, 0x00,
	0xf5, 0x5c, 0xc5, 0xce, 0x2f, 0x18, 0x7d, 0xc3, 0xb2, 0x52, 0xef, 0xa1, 0xaf, 0x6b, 0xba, 0x2f,
	0xd9, 0xd3, 0xc3, 0x87, 0xd2, 0x47, 0x4e, 0x53, 0xe7, 0x74, 0x3e, 0xc3, 0xd8, 0x97, 0x09, 0x7f,
	0x82, 0x4c, 0x67, 0x07, 0xe3, 0x82, 0x1a, 0xf1, 0x58, 0x67, 0xaf, 0xa1, 0xc3, 0xc3, 0xbf, 0x18,
	0x08, 0xba, 0xc7, 0x5c, 0x40, 0xc3, 0x6b, 0xab, 0x80, 0x4f, 0xf7, 0x48, 0xde, 0x00, 0xe4, 0xa0,
	0x4c, 0x2e, 0x90, 0xd9, 0x56, 0x9e, 0x98, 0x7f, 0xfe, 0x53, 0x05, 0x9c, 0x1b, 0x03, 0xec, 0x22,
	0x9f, 0x87, 0x82, 0x27, 0x4c, 0x20, 0xf9, 0x0e, 0x5d, 0xbd, 0x53, 0x61, 0x1b, 0x33, 0x6b, 0xfe,
	0x7c, 0xf1, 0xd6, 0x2d, 0x5f, 0x8b, 0xab, 0x57, 0xf1, 0xce, 0x53, 0xc9, 0x3b, 0xe8, 0x33, 0xbc,
	0x92, 0x81, 0x26, 0xe6, 0x30, 0xab, 0xae, 0x0a, 0xaf, 0x4f, 0x82, 0xae, 0x0d, 0x78, 0xa1, 0xd7,
	0x21, 0x3d, 0x30, 0x4f, 0x1d, 0x9b, 0xb4, 0x7a, 0xd8, 0xfa, 0x82, 0x2d, 0x7d, 0xc1, 0xe4, 0x15,
	0xb4, 0x85, 0x72, 0x4b, 0x10, 0x4a, 0xfb, 0xd9, 0xcc, 0x98, 0x77, 0xbc, 0x56, 0xfe, 0x5e, 0x4a,
	0x32, 0x82, 0x26, 0xb2, 0x58, 0x01, 0x8d, 0x1c, 0x68, 0x20, 0x8b, 0x97, 0x72, 0x71, 0x6b, 0xc1,
	0x4b, 0x5d, 0x84, 0x8f, 0xe9, 0x25, 0x8d, 0x90, 0xfc, 0x87, 0xe1, 0x03, 0xdf, 0x91, 0x8f, 0x95,
	0xe3, 0x28, 0xb7, 0xe8, 0xb4, 0xd6, 0xfc, 0xc8, 0x3f, 0x18, 0x14, 0xbd, 0x43, 0xdc, 0x6a, 0xaa,
	0x32, 0x97, 0xd5, 0x64, 0xfa, 0x03, 0xfd, 0x82, 0x05, 0xc8, 0x87, 0xaa, 0xc4, 0xd2, 0x4b, 0xa9,
	0xc9, 0x23, 0x61, 0x50, 0xb4, 0x5a, 0x75, 0x47, 0xe5, 0x47, 0x30, 0xfd, 0x54, 0xf7, 0xfb, 0xa3,
	0x89, 0xbf, 0x0e, 0x7f, 0x9f, 0x5d, 0x71, 0xca, 0xa3, 0x4d, 0x33, 0xff, 0xbb, 0x7c, 0xb9, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x9f, 0x86, 0x4b, 0xb7, 0x73, 0x04, 0x00, 0x00,
}
