// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package productrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProductParams struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductParams) Reset()         { *m = CreateProductParams{} }
func (m *CreateProductParams) String() string { return proto.CompactTextString(m) }
func (*CreateProductParams) ProtoMessage()    {}
func (*CreateProductParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *CreateProductParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductParams.Unmarshal(m, b)
}
func (m *CreateProductParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductParams.Marshal(b, m, deterministic)
}
func (m *CreateProductParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductParams.Merge(m, src)
}
func (m *CreateProductParams) XXX_Size() int {
	return xxx_messageInfo_CreateProductParams.Size(m)
}
func (m *CreateProductParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductParams proto.InternalMessageInfo

func (m *CreateProductParams) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type GetProductParams struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductParams) Reset()         { *m = GetProductParams{} }
func (m *GetProductParams) String() string { return proto.CompactTextString(m) }
func (*GetProductParams) ProtoMessage()    {}
func (*GetProductParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *GetProductParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductParams.Unmarshal(m, b)
}
func (m *GetProductParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductParams.Marshal(b, m, deterministic)
}
func (m *GetProductParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductParams.Merge(m, src)
}
func (m *GetProductParams) XXX_Size() int {
	return xxx_messageInfo_GetProductParams.Size(m)
}
func (m *GetProductParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductParams proto.InternalMessageInfo

func (m *GetProductParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetProductParams) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateProductParams)(nil), "pepeunlimited.products.CreateProductParams")
	proto.RegisterType((*Product)(nil), "pepeunlimited.products.Product")
	proto.RegisterType((*GetProductParams)(nil), "pepeunlimited.products.GetProductParams")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2b, 0x48, 0x2d, 0x48, 0x2d,
	0xcd, 0xcb, 0xc9, 0xcc, 0xcd, 0x2c, 0x49, 0x4d, 0xd1, 0x83, 0x4a, 0x16, 0x2b, 0xa9, 0x73, 0x09,
	0x3b, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x06, 0x40, 0x44, 0x02, 0x12, 0x8b, 0x12, 0x73, 0x8b, 0x85,
	0x04, 0xb8, 0x98, 0x8b, 0xb3, 0x4b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25,
	0x6d, 0x2e, 0x76, 0xa8, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xb0, 0x1c, 0x73, 0x10, 0x53,
	0x66, 0x0a, 0x4c, 0x31, 0x13, 0x42, 0xb1, 0x33, 0x97, 0x80, 0x7b, 0x6a, 0x09, 0xaa, 0x91, 0xb2,
	0x5c, 0x5c, 0x50, 0x5b, 0xe3, 0xe1, 0xba, 0x39, 0xa1, 0x22, 0x9e, 0x58, 0x0c, 0x31, 0x3a, 0xc1,
	0xc8, 0xc5, 0x07, 0x35, 0x22, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x28, 0x96, 0x8b, 0x17,
	0xc5, 0xb5, 0x42, 0xda, 0x7a, 0xd8, 0xfd, 0xa5, 0x87, 0xc5, 0x53, 0x52, 0xf2, 0xb8, 0x14, 0xc3,
	0x4c, 0x0b, 0xe7, 0xe2, 0x42, 0x38, 0x5b, 0x48, 0x03, 0x97, 0x72, 0x74, 0xaf, 0x11, 0x34, 0xd8,
	0x89, 0x27, 0x0a, 0xe6, 0xf7, 0xa2, 0x82, 0xe4, 0x24, 0x36, 0x70, 0x94, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x63, 0xac, 0x7c, 0x84, 0xa3, 0x01, 0x00, 0x00,
}
