// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProductParams struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductParams) Reset()         { *m = CreateProductParams{} }
func (m *CreateProductParams) String() string { return proto.CompactTextString(m) }
func (*CreateProductParams) ProtoMessage()    {}
func (*CreateProductParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *CreateProductParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductParams.Unmarshal(m, b)
}
func (m *CreateProductParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductParams.Marshal(b, m, deterministic)
}
func (m *CreateProductParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductParams.Merge(m, src)
}
func (m *CreateProductParams) XXX_Size() int {
	return xxx_messageInfo_CreateProductParams.Size(m)
}
func (m *CreateProductParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductParams proto.InternalMessageInfo

func (m *CreateProductParams) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type GetProductParams struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductParams) Reset()         { *m = GetProductParams{} }
func (m *GetProductParams) String() string { return proto.CompactTextString(m) }
func (*GetProductParams) ProtoMessage()    {}
func (*GetProductParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *GetProductParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductParams.Unmarshal(m, b)
}
func (m *GetProductParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductParams.Marshal(b, m, deterministic)
}
func (m *GetProductParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductParams.Merge(m, src)
}
func (m *GetProductParams) XXX_Size() int {
	return xxx_messageInfo_GetProductParams.Size(m)
}
func (m *GetProductParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductParams proto.InternalMessageInfo

func (m *GetProductParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetProductParams) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type GetProductsParams struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            int64    `protobuf:"varint,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsParams) Reset()         { *m = GetProductsParams{} }
func (m *GetProductsParams) String() string { return proto.CompactTextString(m) }
func (*GetProductsParams) ProtoMessage()    {}
func (*GetProductsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *GetProductsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsParams.Unmarshal(m, b)
}
func (m *GetProductsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsParams.Marshal(b, m, deterministic)
}
func (m *GetProductsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsParams.Merge(m, src)
}
func (m *GetProductsParams) XXX_Size() int {
	return xxx_messageInfo_GetProductsParams.Size(m)
}
func (m *GetProductsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsParams proto.InternalMessageInfo

func (m *GetProductsParams) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetProductsParams) GetPageToken() int64 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

type GetProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken        int64      `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(m, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *GetProductsResponse) GetNextPageToken() int64 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateProductParams)(nil), "pepeunlimited.products.CreateProductParams")
	proto.RegisterType((*Product)(nil), "pepeunlimited.products.Product")
	proto.RegisterType((*GetProductParams)(nil), "pepeunlimited.products.GetProductParams")
	proto.RegisterType((*GetProductsParams)(nil), "pepeunlimited.products.GetProductsParams")
	proto.RegisterType((*GetProductsResponse)(nil), "pepeunlimited.products.GetProductsResponse")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x4b, 0x83, 0x50,
	0x14, 0xc6, 0x51, 0xa9, 0xcd, 0x33, 0x5c, 0xeb, 0x0e, 0x62, 0x2c, 0xa2, 0xe1, 0x43, 0x19, 0x82,
	0x0f, 0xeb, 0xb1, 0xb7, 0xf6, 0x10, 0x3d, 0x25, 0x2e, 0x08, 0x82, 0x10, 0x9b, 0x87, 0x71, 0x59,
	0xd3, 0x8b, 0xf7, 0x1a, 0xe1, 0x3f, 0xd5, 0xbf, 0x18, 0xd7, 0xae, 0x73, 0x2b, 0x87, 0x7b, 0x93,
	0xef, 0x7c, 0xe7, 0xf7, 0xe9, 0xf9, 0x04, 0x8b, 0x65, 0x69, 0x9c, 0x2f, 0x84, 0xc7, 0xb2, 0x54,
	0xa4, 0xe4, 0x8c, 0x21, 0xc3, 0x3c, 0xf9, 0xa0, 0x6b, 0x2a, 0x30, 0xf6, 0xd4, 0x90, 0xdb, 0xd7,
	0x30, 0x9c, 0x65, 0x18, 0x09, 0xf4, 0x7f, 0x15, 0x3f, 0xca, 0xa2, 0x35, 0x27, 0x03, 0x30, 0xf8,
	0x2a, 0x1f, 0x69, 0x13, 0xcd, 0x31, 0x03, 0xf9, 0x68, 0xbb, 0xd0, 0x51, 0x16, 0xd2, 0x07, 0x9d,
	0xc6, 0xe5, 0xcc, 0x08, 0x74, 0x1a, 0x57, 0x66, 0xbd, 0x36, 0xcf, 0x60, 0xf0, 0x80, 0x62, 0x17,
	0x79, 0x01, 0xa0, 0x52, 0xc3, 0xcd, 0xb6, 0xa9, 0x94, 0xc7, 0x26, 0xc8, 0x13, 0x9c, 0xd6, 0x10,
	0xae, 0x28, 0xe7, 0x60, 0xb2, 0x68, 0x89, 0x21, 0xa7, 0x05, 0x96, 0x90, 0xa3, 0xa0, 0x2b, 0x85,
	0x39, 0x2d, 0xb0, 0x8c, 0x90, 0x43, 0x91, 0xae, 0x30, 0x29, 0x51, 0x32, 0x22, 0x5a, 0xe2, 0xb3,
	0x14, 0xec, 0x02, 0x86, 0x5b, 0xc0, 0x00, 0x39, 0x4b, 0x13, 0x8e, 0xe4, 0x0e, 0xba, 0xd5, 0x39,
	0x46, 0xda, 0xc4, 0x70, 0x7a, 0xd3, 0x4b, 0xaf, 0xf9, 0x5a, 0x9e, 0xda, 0x0d, 0x36, 0x0b, 0xe4,
	0x0a, 0x4e, 0x12, 0xfc, 0x12, 0xe1, 0xbf, 0x5c, 0x4b, 0xca, 0x7e, 0x95, 0x3d, 0xfd, 0xd6, 0xa1,
	0xaf, 0xb6, 0xe7, 0x98, 0x7d, 0xd2, 0x05, 0x92, 0x37, 0xb0, 0x76, 0x4e, 0x4f, 0xdc, 0x7d, 0xb1,
	0x0d, 0x0d, 0x8d, 0xdb, 0xde, 0x91, 0xbc, 0x00, 0xd4, 0x5f, 0x4b, 0x9c, 0x7d, 0xf6, 0xbf, 0x3d,
	0xb5, 0x83, 0x11, 0x7a, 0x5b, 0x67, 0x24, 0x37, 0xed, 0x64, 0x55, 0xde, 0xd8, 0x3d, 0xc0, 0x5a,
	0xd5, 0x72, 0x6f, 0xbe, 0x76, 0xd4, 0xfc, 0xfd, 0xb8, 0xfc, 0x87, 0x6f, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x03, 0x7e, 0x4e, 0x85, 0xd4, 0x02, 0x00, 0x00,
}
