// Code generated by entc, DO NOT EDIT.

package price

const (
	// Label holds the string label denoting the price type in the database.
	Label = "price"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartAt holds the string denoting the start_at vertex property in the database.
	FieldStartAt = "start_at"
	// FieldEndAt holds the string denoting the end_at vertex property in the database.
	FieldEndAt = "end_at"
	// FieldCost holds the string denoting the cost vertex property in the database.
	FieldCost = "cost"
	// FieldDiscount holds the string denoting the discount vertex property in the database.
	FieldDiscount = "discount"

	// Table holds the table name of the price in the database.
	Table = "prices"
)

// Columns holds all SQL columns for price fields.
var Columns = []string{
	FieldID,
	FieldStartAt,
	FieldEndAt,
	FieldCost,
	FieldDiscount,
}
