// Code generated by entc, DO NOT EDIT.

package price

const (
	// Label holds the string label denoting the price type in the database.
	Label = "price"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartAt holds the string denoting the start_at vertex property in the database.
	FieldStartAt = "start_at"
	// FieldEndAt holds the string denoting the end_at vertex property in the database.
	FieldEndAt = "end_at"
	// FieldPrice holds the string denoting the price vertex property in the database.
	FieldPrice = "price"
	// FieldDiscount holds the string denoting the discount vertex property in the database.
	FieldDiscount = "discount"

	// Table holds the table name of the price in the database.
	Table = "prices"
	// ProductsTable is the table the holds the products relation/edge.
	ProductsTable = "prices"
	// ProductsInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductsInverseTable = "products"
	// ProductsColumn is the table column denoting the products relation/edge.
	ProductsColumn = "product_prices"
	// ThirdPartyPricesTable is the table the holds the third_party_prices relation/edge.
	ThirdPartyPricesTable = "prices"
	// ThirdPartyPricesInverseTable is the table name for the ThirdPartyPrice entity.
	// It exists in this package in order to avoid circular dependency with the "thirdpartyprice" package.
	ThirdPartyPricesInverseTable = "third_party_prices"
	// ThirdPartyPricesColumn is the table column denoting the third_party_prices relation/edge.
	ThirdPartyPricesColumn = "third_party_price_prices"
)

// Columns holds all SQL columns for price fields.
var Columns = []string{
	FieldID,
	FieldStartAt,
	FieldEndAt,
	FieldPrice,
	FieldDiscount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Price type.
var ForeignKeys = []string{
	"product_prices",
	"third_party_price_prices",
}
