// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plan.proto

package planrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePlanParams struct {
	TitleI18NId          int64    `protobuf:"varint,1,opt,name=title_i18n_id,json=titleI18nId,proto3" json:"title_i18n_id,omitempty"`
	Length               int32    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanParams) Reset()         { *m = CreatePlanParams{} }
func (m *CreatePlanParams) String() string { return proto.CompactTextString(m) }
func (*CreatePlanParams) ProtoMessage()    {}
func (*CreatePlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{0}
}

func (m *CreatePlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanParams.Unmarshal(m, b)
}
func (m *CreatePlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanParams.Marshal(b, m, deterministic)
}
func (m *CreatePlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanParams.Merge(m, src)
}
func (m *CreatePlanParams) XXX_Size() int {
	return xxx_messageInfo_CreatePlanParams.Size(m)
}
func (m *CreatePlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanParams proto.InternalMessageInfo

func (m *CreatePlanParams) GetTitleI18NId() int64 {
	if m != nil {
		return m.TitleI18NId
	}
	return 0
}

func (m *CreatePlanParams) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *CreatePlanParams) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type Plan struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TitleI18NId          int64    `protobuf:"varint,2,opt,name=title_i18n_id,json=titleI18nId,proto3" json:"title_i18n_id,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Length               int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{1}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plan) GetTitleI18NId() int64 {
	if m != nil {
		return m.TitleI18NId
	}
	return 0
}

func (m *Plan) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Plan) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type GetPlanParams struct {
	PlanId               int64    `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanParams) Reset()         { *m = GetPlanParams{} }
func (m *GetPlanParams) String() string { return proto.CompactTextString(m) }
func (*GetPlanParams) ProtoMessage()    {}
func (*GetPlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{2}
}

func (m *GetPlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanParams.Unmarshal(m, b)
}
func (m *GetPlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanParams.Marshal(b, m, deterministic)
}
func (m *GetPlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanParams.Merge(m, src)
}
func (m *GetPlanParams) XXX_Size() int {
	return xxx_messageInfo_GetPlanParams.Size(m)
}
func (m *GetPlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanParams proto.InternalMessageInfo

func (m *GetPlanParams) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

type GetPlansParams struct {
	Show                 bool     `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlansParams) Reset()         { *m = GetPlansParams{} }
func (m *GetPlansParams) String() string { return proto.CompactTextString(m) }
func (*GetPlansParams) ProtoMessage()    {}
func (*GetPlansParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{3}
}

func (m *GetPlansParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlansParams.Unmarshal(m, b)
}
func (m *GetPlansParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlansParams.Marshal(b, m, deterministic)
}
func (m *GetPlansParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlansParams.Merge(m, src)
}
func (m *GetPlansParams) XXX_Size() int {
	return xxx_messageInfo_GetPlansParams.Size(m)
}
func (m *GetPlansParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlansParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlansParams proto.InternalMessageInfo

func (m *GetPlansParams) GetShow() bool {
	if m != nil {
		return m.Show
	}
	return false
}

type GetPlansResponse struct {
	Plans                []*Plan  `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlansResponse) Reset()         { *m = GetPlansResponse{} }
func (m *GetPlansResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlansResponse) ProtoMessage()    {}
func (*GetPlansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{4}
}

func (m *GetPlansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlansResponse.Unmarshal(m, b)
}
func (m *GetPlansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlansResponse.Marshal(b, m, deterministic)
}
func (m *GetPlansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlansResponse.Merge(m, src)
}
func (m *GetPlansResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlansResponse.Size(m)
}
func (m *GetPlansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlansResponse proto.InternalMessageInfo

func (m *GetPlansResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePlanParams)(nil), "pepeunlimited.products.CreatePlanParams")
	proto.RegisterType((*Plan)(nil), "pepeunlimited.products.Plan")
	proto.RegisterType((*GetPlanParams)(nil), "pepeunlimited.products.GetPlanParams")
	proto.RegisterType((*GetPlansParams)(nil), "pepeunlimited.products.GetPlansParams")
	proto.RegisterType((*GetPlansResponse)(nil), "pepeunlimited.products.GetPlansResponse")
}

func init() { proto.RegisterFile("plan.proto", fileDescriptor_2d655ab2f7683c23) }

var fileDescriptor_2d655ab2f7683c23 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xd3, 0x52, 0xfe, 0x0d, 0x81, 0x90, 0x39, 0x60, 0x43, 0x3c, 0x34, 0x8d, 0x9a, 0x3d,
	0x91, 0x80, 0x17, 0xce, 0x9a, 0x68, 0xb8, 0x18, 0x52, 0x3d, 0x19, 0x13, 0x52, 0xe8, 0x28, 0x9b,
	0x94, 0xed, 0xa6, 0xbb, 0xe8, 0xe7, 0xf0, 0x1b, 0x9b, 0x5d, 0x0b, 0x54, 0x01, 0xf1, 0xb6, 0x33,
	0xf9, 0xed, 0x7b, 0xfb, 0x66, 0x16, 0x40, 0xa6, 0xb1, 0x18, 0xc8, 0x3c, 0xd3, 0x19, 0xf6, 0x24,
	0x49, 0x5a, 0x8b, 0x94, 0xaf, 0xb8, 0xa6, 0xc4, 0x34, 0x93, 0xf5, 0x42, 0xab, 0x70, 0x0e, 0xdd,
	0xdb, 0x9c, 0x62, 0x4d, 0xd3, 0x34, 0x16, 0xd3, 0x38, 0x8f, 0x57, 0x0a, 0x43, 0x68, 0x6b, 0xae,
	0x53, 0x9a, 0xf1, 0xe1, 0x58, 0xcc, 0x78, 0xe2, 0x3b, 0x81, 0xc3, 0x2a, 0x51, 0xcb, 0x36, 0x27,
	0xc3, 0xb1, 0x98, 0x24, 0xd8, 0x83, 0x5a, 0x4a, 0xe2, 0x4d, 0x2f, 0x7d, 0x37, 0x70, 0x58, 0x35,
	0x2a, 0x2a, 0x44, 0xf0, 0xd6, 0x82, 0x6b, 0xbf, 0x12, 0x38, 0xac, 0x19, 0xd9, 0x73, 0xf8, 0x0a,
	0x9e, 0x51, 0xc7, 0x0e, 0xb8, 0x5b, 0x31, 0x97, 0x27, 0xfb, 0x3e, 0xee, 0xbe, 0xcf, 0x01, 0xbd,
	0x92, 0xb7, 0x57, 0xf6, 0x0e, 0x19, 0xb4, 0xef, 0x49, 0x97, 0x82, 0x9c, 0x41, 0xdd, 0x8c, 0x60,
	0x17, 0xa1, 0x66, 0xca, 0x49, 0x12, 0x5e, 0x40, 0xa7, 0x20, 0x55, 0x81, 0x22, 0x78, 0x6a, 0x99,
	0x7d, 0x58, 0xae, 0x11, 0xd9, 0x73, 0x78, 0x07, 0xdd, 0x0d, 0x15, 0x91, 0x92, 0x99, 0x50, 0x84,
	0x23, 0xa8, 0x1a, 0x0d, 0xe5, 0x3b, 0x41, 0x85, 0xb5, 0x46, 0xe7, 0x83, 0xc3, 0x73, 0x1d, 0x98,
	0x5b, 0xd1, 0x37, 0x3a, 0xfa, 0x74, 0xa1, 0x65, 0xea, 0x47, 0xca, 0xdf, 0xf9, 0x82, 0xf0, 0x09,
	0x60, 0x37, 0x73, 0x64, 0xc7, 0x24, 0x7e, 0xef, 0xa5, 0xff, 0xa7, 0x19, 0xbe, 0x40, 0x63, 0xf3,
	0x5a, 0xbc, 0x3a, 0x46, 0xfe, 0x4c, 0xdd, 0x67, 0xa7, 0xb8, 0x6d, 0xee, 0x07, 0xa8, 0x17, 0x3d,
	0xbc, 0x3c, 0x71, 0xe9, 0x3f, 0xaf, 0xbd, 0x69, 0x3e, 0xdb, 0xd5, 0xe4, 0x72, 0x31, 0xaf, 0xd9,
	0x1f, 0x7a, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x67, 0x96, 0x28, 0xe6, 0xaf, 0x02, 0x00, 0x00,
}
