// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Plan is the predicate function for plan builders.
type Plan func(*sql.Selector)

// Price is the predicate function for price builders.
type Price func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// ThirdParty is the predicate function for thirdparty builders.
type ThirdParty func(*sql.Selector)
