// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plan.proto

package plan

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePlanParams struct {
	TitleI18NId          int64    `protobuf:"varint,1,opt,name=title_i18n_id,json=titleI18nId,proto3" json:"title_i18n_id,omitempty"`
	Length               int32    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	StartAtDay           int32    `protobuf:"varint,4,opt,name=start_at_day,json=startAtDay,proto3" json:"start_at_day,omitempty"`
	StartAtMonth         int32    `protobuf:"varint,5,opt,name=start_at_month,json=startAtMonth,proto3" json:"start_at_month,omitempty"`
	EndAtDay             int32    `protobuf:"varint,6,opt,name=end_at_day,json=endAtDay,proto3" json:"end_at_day,omitempty"`
	EndAtMonth           int32    `protobuf:"varint,7,opt,name=end_at_month,json=endAtMonth,proto3" json:"end_at_month,omitempty"`
	Price                uint32   `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Discount             uint32   `protobuf:"varint,9,opt,name=discount,proto3" json:"discount,omitempty"`
	ProductId            int64    `protobuf:"varint,10,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ThirdPartyPriceId    int32    `protobuf:"varint,11,opt,name=third_party_price_id,json=thirdPartyPriceId,proto3" json:"third_party_price_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanParams) Reset()         { *m = CreatePlanParams{} }
func (m *CreatePlanParams) String() string { return proto.CompactTextString(m) }
func (*CreatePlanParams) ProtoMessage()    {}
func (*CreatePlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{0}
}

func (m *CreatePlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanParams.Unmarshal(m, b)
}
func (m *CreatePlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanParams.Marshal(b, m, deterministic)
}
func (m *CreatePlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanParams.Merge(m, src)
}
func (m *CreatePlanParams) XXX_Size() int {
	return xxx_messageInfo_CreatePlanParams.Size(m)
}
func (m *CreatePlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanParams proto.InternalMessageInfo

func (m *CreatePlanParams) GetTitleI18NId() int64 {
	if m != nil {
		return m.TitleI18NId
	}
	return 0
}

func (m *CreatePlanParams) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *CreatePlanParams) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *CreatePlanParams) GetStartAtDay() int32 {
	if m != nil {
		return m.StartAtDay
	}
	return 0
}

func (m *CreatePlanParams) GetStartAtMonth() int32 {
	if m != nil {
		return m.StartAtMonth
	}
	return 0
}

func (m *CreatePlanParams) GetEndAtDay() int32 {
	if m != nil {
		return m.EndAtDay
	}
	return 0
}

func (m *CreatePlanParams) GetEndAtMonth() int32 {
	if m != nil {
		return m.EndAtMonth
	}
	return 0
}

func (m *CreatePlanParams) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreatePlanParams) GetDiscount() uint32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *CreatePlanParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *CreatePlanParams) GetThirdPartyPriceId() int32 {
	if m != nil {
		return m.ThirdPartyPriceId
	}
	return 0
}

type Plan struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TitleI18NId          int64    `protobuf:"varint,2,opt,name=title_i18n_id,json=titleI18nId,proto3" json:"title_i18n_id,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Length               int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Price                uint32   `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Discount             uint32   `protobuf:"varint,6,opt,name=discount,proto3" json:"discount,omitempty"`
	StartAt              string   `protobuf:"bytes,7,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                string   `protobuf:"bytes,8,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	ThirdPartyPriceId    int32    `protobuf:"varint,9,opt,name=third_party_price_id,json=thirdPartyPriceId,proto3" json:"third_party_price_id,omitempty"`
	ProductId            int64    `protobuf:"varint,10,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{1}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plan) GetTitleI18NId() int64 {
	if m != nil {
		return m.TitleI18NId
	}
	return 0
}

func (m *Plan) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Plan) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Plan) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Plan) GetDiscount() uint32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Plan) GetStartAt() string {
	if m != nil {
		return m.StartAt
	}
	return ""
}

func (m *Plan) GetEndAt() string {
	if m != nil {
		return m.EndAt
	}
	return ""
}

func (m *Plan) GetThirdPartyPriceId() int32 {
	if m != nil {
		return m.ThirdPartyPriceId
	}
	return 0
}

func (m *Plan) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type GetPlanParams struct {
	PlanId               int64    `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanParams) Reset()         { *m = GetPlanParams{} }
func (m *GetPlanParams) String() string { return proto.CompactTextString(m) }
func (*GetPlanParams) ProtoMessage()    {}
func (*GetPlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{2}
}

func (m *GetPlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanParams.Unmarshal(m, b)
}
func (m *GetPlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanParams.Marshal(b, m, deterministic)
}
func (m *GetPlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanParams.Merge(m, src)
}
func (m *GetPlanParams) XXX_Size() int {
	return xxx_messageInfo_GetPlanParams.Size(m)
}
func (m *GetPlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanParams proto.InternalMessageInfo

func (m *GetPlanParams) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

type GetPlansParams struct {
	ProductId            int64    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductSku           string   `protobuf:"bytes,3,opt,name=product_sku,json=productSku,proto3" json:"product_sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlansParams) Reset()         { *m = GetPlansParams{} }
func (m *GetPlansParams) String() string { return proto.CompactTextString(m) }
func (*GetPlansParams) ProtoMessage()    {}
func (*GetPlansParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{3}
}

func (m *GetPlansParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlansParams.Unmarshal(m, b)
}
func (m *GetPlansParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlansParams.Marshal(b, m, deterministic)
}
func (m *GetPlansParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlansParams.Merge(m, src)
}
func (m *GetPlansParams) XXX_Size() int {
	return xxx_messageInfo_GetPlansParams.Size(m)
}
func (m *GetPlansParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlansParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlansParams proto.InternalMessageInfo

func (m *GetPlansParams) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetPlansParams) GetProductSku() string {
	if m != nil {
		return m.ProductSku
	}
	return ""
}

type GetPlansResponse struct {
	Plans                []*Plan  `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlansResponse) Reset()         { *m = GetPlansResponse{} }
func (m *GetPlansResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlansResponse) ProtoMessage()    {}
func (*GetPlansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{4}
}

func (m *GetPlansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlansResponse.Unmarshal(m, b)
}
func (m *GetPlansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlansResponse.Marshal(b, m, deterministic)
}
func (m *GetPlansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlansResponse.Merge(m, src)
}
func (m *GetPlansResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlansResponse.Size(m)
}
func (m *GetPlansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlansResponse proto.InternalMessageInfo

func (m *GetPlansResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type EndPlanAtParams struct {
	PlanId               int64    `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	EndAtDay             int32    `protobuf:"varint,2,opt,name=end_at_day,json=endAtDay,proto3" json:"end_at_day,omitempty"`
	EndAtMonth           int32    `protobuf:"varint,3,opt,name=end_at_month,json=endAtMonth,proto3" json:"end_at_month,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndPlanAtParams) Reset()         { *m = EndPlanAtParams{} }
func (m *EndPlanAtParams) String() string { return proto.CompactTextString(m) }
func (*EndPlanAtParams) ProtoMessage()    {}
func (*EndPlanAtParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d655ab2f7683c23, []int{5}
}

func (m *EndPlanAtParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndPlanAtParams.Unmarshal(m, b)
}
func (m *EndPlanAtParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndPlanAtParams.Marshal(b, m, deterministic)
}
func (m *EndPlanAtParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndPlanAtParams.Merge(m, src)
}
func (m *EndPlanAtParams) XXX_Size() int {
	return xxx_messageInfo_EndPlanAtParams.Size(m)
}
func (m *EndPlanAtParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EndPlanAtParams.DiscardUnknown(m)
}

var xxx_messageInfo_EndPlanAtParams proto.InternalMessageInfo

func (m *EndPlanAtParams) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

func (m *EndPlanAtParams) GetEndAtDay() int32 {
	if m != nil {
		return m.EndAtDay
	}
	return 0
}

func (m *EndPlanAtParams) GetEndAtMonth() int32 {
	if m != nil {
		return m.EndAtMonth
	}
	return 0
}

func init() {
	proto.RegisterType((*CreatePlanParams)(nil), "pepeunlimited.products.CreatePlanParams")
	proto.RegisterType((*Plan)(nil), "pepeunlimited.products.Plan")
	proto.RegisterType((*GetPlanParams)(nil), "pepeunlimited.products.GetPlanParams")
	proto.RegisterType((*GetPlansParams)(nil), "pepeunlimited.products.GetPlansParams")
	proto.RegisterType((*GetPlansResponse)(nil), "pepeunlimited.products.GetPlansResponse")
	proto.RegisterType((*EndPlanAtParams)(nil), "pepeunlimited.products.EndPlanAtParams")
}

func init() { proto.RegisterFile("plan.proto", fileDescriptor_2d655ab2f7683c23) }

var fileDescriptor_2d655ab2f7683c23 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0x27, 0x76, 0xe2, 0x49, 0x13, 0xca, 0xaa, 0x14, 0x13, 0x15, 0x61, 0x59, 0x7c,
	0xf8, 0x14, 0xd4, 0x70, 0xe9, 0xb5, 0x7c, 0x2a, 0x07, 0x90, 0xe5, 0x72, 0x42, 0x48, 0xd6, 0x92,
	0x5d, 0x91, 0xa5, 0xce, 0xda, 0xb2, 0xd7, 0x48, 0x79, 0x15, 0xde, 0x8f, 0x1b, 0x0f, 0x81, 0x76,
	0xbd, 0x76, 0x88, 0x5b, 0xd7, 0xdc, 0xb2, 0x33, 0xff, 0x99, 0xf5, 0xfc, 0xfe, 0xb3, 0x01, 0xc8,
	0x12, 0xcc, 0x17, 0x59, 0x9e, 0x8a, 0x14, 0x9d, 0x66, 0x34, 0xa3, 0x25, 0x4f, 0xd8, 0x96, 0x09,
	0x4a, 0x64, 0x90, 0x94, 0x6b, 0x51, 0xf8, 0x7f, 0x4c, 0x38, 0x7e, 0x93, 0x53, 0x2c, 0x68, 0x98,
	0x60, 0x1e, 0xe2, 0x1c, 0x6f, 0x0b, 0xe4, 0xc3, 0x54, 0x30, 0x91, 0xd0, 0x98, 0x9d, 0x5f, 0xf0,
	0x98, 0x11, 0xd7, 0xf0, 0x8c, 0x60, 0x10, 0x4d, 0x54, 0x70, 0x75, 0x7e, 0xc1, 0x57, 0x04, 0x9d,
	0x82, 0x9d, 0x50, 0xfe, 0x5d, 0x6c, 0x5c, 0xd3, 0x33, 0x02, 0x2b, 0xd2, 0x27, 0x84, 0x60, 0x58,
	0x72, 0x26, 0xdc, 0x81, 0x67, 0x04, 0x4e, 0xa4, 0x7e, 0x23, 0x0f, 0x8e, 0x0a, 0x81, 0x73, 0x11,
	0x63, 0x11, 0x13, 0xbc, 0x73, 0x87, 0xaa, 0x02, 0x54, 0xec, 0x52, 0xbc, 0xc5, 0x3b, 0xf4, 0x14,
	0x66, 0x8d, 0x62, 0x9b, 0x72, 0xb1, 0x71, 0x2d, 0xa5, 0x39, 0xd2, 0x9a, 0x8f, 0x32, 0x86, 0xce,
	0x00, 0x28, 0x27, 0x75, 0x17, 0x5b, 0x29, 0xc6, 0x94, 0x93, 0xaa, 0x87, 0x07, 0x47, 0x3a, 0x5b,
	0x75, 0x18, 0x55, 0xb7, 0xa8, 0x7c, 0x55, 0x7f, 0x02, 0x56, 0x96, 0xb3, 0x35, 0x75, 0xc7, 0x9e,
	0x11, 0x4c, 0xa3, 0xea, 0x80, 0xe6, 0x30, 0x26, 0xac, 0x58, 0xa7, 0x25, 0x17, 0xae, 0xa3, 0x12,
	0xcd, 0x19, 0x3d, 0x06, 0xd0, 0xa8, 0x24, 0x06, 0x50, 0x18, 0x1c, 0x1d, 0x59, 0x11, 0xf4, 0x12,
	0x4e, 0xc4, 0x86, 0xe5, 0x24, 0xce, 0x70, 0x2e, 0x76, 0xb1, 0xea, 0x27, 0x85, 0x13, 0x75, 0xf5,
	0x7d, 0x95, 0x0b, 0x65, 0x2a, 0x94, 0x99, 0x15, 0xf1, 0x7f, 0x99, 0x30, 0x94, 0xa0, 0xd1, 0x0c,
	0xcc, 0x86, 0xab, 0xc9, 0xc8, 0x4d, 0xe4, 0xe6, 0x4d, 0xe4, 0xb7, 0xa1, 0xdd, 0xdb, 0x30, 0x3c,
	0xb0, 0xa1, 0x19, 0xd5, 0xea, 0x1a, 0xd5, 0x6e, 0x8d, 0xfa, 0x08, 0xc6, 0xb5, 0x05, 0x0a, 0x9d,
	0x13, 0x8d, 0x34, 0x7c, 0xf4, 0x00, 0xec, 0x8a, 0xac, 0x02, 0xe7, 0x44, 0x96, 0x62, 0xda, 0x39,
	0xbd, 0xd3, 0x31, 0x7d, 0x0f, 0x4d, 0x3f, 0x80, 0xe9, 0x07, 0x2a, 0xfe, 0xd9, 0xc3, 0x87, 0x30,
	0x92, 0x2b, 0xbc, 0xdf, 0x40, 0x5b, 0x1e, 0x57, 0xc4, 0x0f, 0x61, 0xa6, 0x95, 0x85, 0x96, 0x1e,
	0xb6, 0x36, 0xdb, 0x46, 0x3d, 0x81, 0x49, 0x9d, 0x2e, 0xae, 0x4b, 0x4d, 0xb0, 0xae, 0xb8, 0xba,
	0x2e, 0xfd, 0xf7, 0x70, 0x5c, 0x77, 0x8c, 0x68, 0x91, 0xa5, 0xbc, 0xa0, 0x68, 0x09, 0x96, 0xbc,
	0xaf, 0x70, 0x0d, 0x6f, 0x10, 0x4c, 0x96, 0x67, 0x8b, 0xdb, 0xdf, 0xd0, 0x42, 0x56, 0x45, 0x95,
	0xd4, 0xff, 0x01, 0xf7, 0xde, 0x71, 0x22, 0x23, 0x97, 0xa2, 0x67, 0x8a, 0xd6, 0x3a, 0x9b, 0x3d,
	0xeb, 0x3c, 0x68, 0xaf, 0xf3, 0xf2, 0xb7, 0x09, 0x13, 0x79, 0xd3, 0x15, 0xcd, 0x7f, 0x4a, 0x77,
	0x3f, 0x03, 0xec, 0x9f, 0x32, 0x0a, 0xba, 0x3e, 0xb7, 0xfd, 0xdc, 0xe7, 0x77, 0x0e, 0x86, 0xbe,
	0xc2, 0xb8, 0x26, 0x83, 0x9e, 0x77, 0x29, 0x0f, 0xdd, 0x98, 0x07, 0x7d, 0xba, 0x86, 0xf1, 0x27,
	0x18, 0xe9, 0x18, 0x7a, 0xd6, 0x53, 0xf4, 0x5f, 0x5f, 0x1b, 0x81, 0xd3, 0xf0, 0x47, 0x2f, 0xba,
	0xa4, 0x2d, 0x8b, 0xee, 0xee, 0xf9, 0xda, 0xfe, 0x32, 0x94, 0x8e, 0x7d, 0xb3, 0xd5, 0x5f, 0xe9,
	0xab, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xbc, 0x8a, 0xd4, 0x58, 0x05, 0x00, 0x00,
}
